title: Learn Equine Studies
description: >
  A free, comprehensive resource for equine studies and compassionate horsemanship.
baseurl: "/learn-equine-studies"
url: "https://dandelionx86.github.io"

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme

color_scheme: dark
